"""Initial migration or added new models

Revision ID: 37ee537db29f
Revises: 
Create Date: 2024-11-05 18:41:09.886869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '37ee537db29f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logged_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('local_storage', sa.JSON(), nullable=True))
        batch_op.drop_column('local_storage_cookie')
        batch_op.drop_column('visit_timestamp')
        batch_op.drop_column('phone_prefix')
        batch_op.drop_column('username')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logged_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=256), nullable=False))
        batch_op.add_column(sa.Column('phone_prefix', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('visit_timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('local_storage_cookie', sqlite.JSON(), nullable=True))
        batch_op.drop_column('local_storage')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
